"use strict"
/**
 * Auto-generated TypeScript types from Strapi
 *
 * Generated on: 2025-11-16T14:04:48.073Z
 * Strapi URL: http://localhost:1337
 *
 * DO NOT EDIT THIS FILE MANUALLY
 * Regenerate with: yarn generate:types
 */
Object.defineProperty(exports, "__esModule", { value: true })
