/**
 * Auto-generated TypeScript types from Strapi
 *
 * Generated on: 2025-11-16T14:04:48.073Z
 * Strapi URL: http://localhost:1337
 *
 * DO NOT EDIT THIS FILE MANUALLY
 * Regenerate with: yarn generate:types
 */

// ==========================================
// Base Types
// ==========================================

export interface StrapiMedia {
  id: number
  name: string
  alternativeText: string | null
  caption: string | null
  width: number | null
  height: number | null
  formats: {
    thumbnail?: StrapiMediaFormat
    small?: StrapiMediaFormat
    medium?: StrapiMediaFormat
    large?: StrapiMediaFormat
  } | null
  hash: string
  ext: string
  mime: string
  size: number
  url: string
  previewUrl: string | null
  provider: string
  createdAt: string
  updatedAt: string
}

export interface StrapiMediaFormat {
  name: string
  hash: string
  ext: string
  mime: string
  width: number
  height: number
  size: number
  path: string | null
  url: string
}

export interface StrapiResponse<T> {
  data: T
  meta: {
    pagination?: {
      page: number
      pageSize: number
      pageCount: number
      total: number
    }
  }
}

// ==========================================
// Content Types
// ==========================================

/**
 * Footer
 * Collection: footers
 */
export interface Footer {
  id: number
  sections: any[]
  copyRight: string | null
  logoImage: any | null
  description: string | null
  companyTitle: string | null
  socialLinks: any[]
  newsletter: any | null
  createdAt: string
  updatedAt: string
}

/**
 * InternalJob
 * Collection: internal_jobs
 */
export interface InternalJob {
  id: number
  jobType: string
  relatedDocumentId: string | null
  payload: any
  state: string
  error: string | null
  createdAt: string
  updatedAt: string
}

/**
 * Navbar
 * Collection: navbars
 */
export interface Navbar {
  id: number
  links: any[]
  logoImage: any | null
  socialLinks: any[]
  createdAt: string
  updatedAt: string
}

/**
 * Page
 * Collection: pages
 */
export interface Page {
  id: number
  title: string
  breadcrumbTitle: string | null
  slug: string
  fullPath: string | null
  content: any[] | null
  parent: any | null
  children: any | null
  seo: any | null
  createdAt: string
  updatedAt: string
  publishedAt: string | null
}

/**
 * Redirect
 * Collection: redirects
 */
export interface Redirect {
  id: number
  source: string
  destination: string
  permanent: boolean | null
  page: any | null
  createdAt: string
  updatedAt: string
  publishedAt: string | null
}

/**
 * Subscriber
 * Collection: subscribers
 */
export interface Subscriber {
  id: number
  name: string | null
  email: string | null
  message: string | null
  createdAt: string
  updatedAt: string
}
