#!/usr/bin/env node

/**
 * TypeScript Type Generation from Strapi Schema
 *
 * Automatically generates TypeScript types from Strapi content types
 * Run manually: yarn generate:types
 * Run on schema changes: via webhook (future enhancement)
 *
 * @see docs/strapi-integration/03-TYPE-GENERATION.md
 * @see docs/AUTOMATION-STRATEGY.md
 */

const fs = require("fs")
const path = require("path")
const https = require("https")
const http = require("http")

// Load environment variables from .env file
try {
  const dotenv = require("dotenv")
  const envPath = path.join(__dirname, "..", ".env")
  if (fs.existsSync(envPath)) {
    dotenv.config({ path: envPath })
  }
} catch (error) {
  // dotenv not installed, continue with process.env
}

// Configuration
const STRAPI_URL = process.env.STRAPI_API_URL || "http://localhost:1337"
const STRAPI_TOKEN = process.env.STRAPI_API_TOKEN
const OUTPUT_FILE = path.join(
  __dirname,
  "../packages/shared-data/strapi-types.ts"
)

console.log("🔄 Generating TypeScript types from Strapi...\n")

if (!STRAPI_TOKEN) {
  console.error("❌ STRAPI_API_TOKEN environment variable is required")
  console.log(
    "   Set it in your .env.local file or pass as environment variable"
  )
  console.log("   Example: STRAPI_API_TOKEN=your_token yarn generate:types\n")
  process.exit(1)
}

/**
 * Fetch content types from Strapi
 */
async function fetchContentTypes() {
  return new Promise((resolve, reject) => {
    const url = new URL("/api/content-type-builder/content-types", STRAPI_URL)
    const protocol = url.protocol === "https:" ? https : http

    const options = {
      method: "GET",
      headers: {
        Authorization: `Bearer ${STRAPI_TOKEN}`,
        "Content-Type": "application/json",
      },
    }

    console.log(`📡 Fetching from: ${url.toString()}`)

    const req = protocol.request(url, options, (res) => {
      let data = ""

      res.on("data", (chunk) => {
        data += chunk
      })

      res.on("end", () => {
        if (res.statusCode === 200) {
          try {
            const parsed = JSON.parse(data)
            resolve(parsed.data)
          } catch (error) {
            reject(new Error(`Failed to parse response: ${error.message}`))
          }
        } else {
          reject(new Error(`HTTP ${res.statusCode}: ${data}`))
        }
      })
    })

    req.on("error", (error) => {
      reject(error)
    })

    req.end()
  })
}

/**
 * Convert Strapi field type to TypeScript type
 */
function strapiTypeToTS(field) {
  const typeMap = {
    string: "string",
    text: "string",
    richtext: "string",
    email: "string",
    password: "string",
    uid: "string",
    enumeration: "string",
    integer: "number",
    biginteger: "number",
    float: "number",
    decimal: "number",
    boolean: "boolean",
    date: "string",
    time: "string",
    datetime: "string",
    timestamp: "string",
    json: "any",
    media: "StrapiMedia",
    relation: "any", // Relations are complex, simplified for now
    component: "any",
    dynamiczone: "any[]",
  }

  const baseType = typeMap[field.type] || "any"

  // Handle arrays (repeatable)
  if (field.repeatable || field.multiple) {
    return `${baseType}[]`
  }

  // Handle optional fields
  if (!field.required) {
    return `${baseType} | null`
  }

  return baseType
}

/**
 * Generate TypeScript interface from content type
 */
function generateInterface(contentType) {
  const { apiID, schema } = contentType
  const interfaceName = apiID
    .split("-")
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join("")

  let output = `\n/**\n * ${schema.displayName || interfaceName}\n`
  if (schema.description) {
    output += ` * ${schema.description}\n`
  }
  output += ` * Collection: ${schema.collectionName}\n`
  output += ` */\n`
  output += `export interface ${interfaceName} {\n`
  output += `  id: number;\n`

  // Add fields
  Object.entries(schema.attributes).forEach(([fieldName, field]) => {
    const tsType = strapiTypeToTS(field)
    output += `  ${fieldName}: ${tsType};\n`
  })

  // Add timestamps (Strapi default fields)
  output += `  createdAt: string;\n`
  output += `  updatedAt: string;\n`
  if (schema.draftAndPublish !== false) {
    output += `  publishedAt: string | null;\n`
  }

  output += `}\n`

  return output
}

/**
 * Main generation function
 */
async function generateTypes() {
  try {
    console.log("📥 Fetching content types from Strapi...")
    const contentTypes = await fetchContentTypes()

    console.log(`✅ Found ${contentTypes.length} content types\n`)

    // Generate header
    let output = `/**
 * Auto-generated TypeScript types from Strapi
 * 
 * Generated on: ${new Date().toISOString()}
 * Strapi URL: ${STRAPI_URL}
 * 
 * DO NOT EDIT THIS FILE MANUALLY
 * Regenerate with: yarn generate:types
 */

// ==========================================
// Base Types
// ==========================================

export interface StrapiMedia {
  id: number;
  name: string;
  alternativeText: string | null;
  caption: string | null;
  width: number | null;
  height: number | null;
  formats: {
    thumbnail?: StrapiMediaFormat;
    small?: StrapiMediaFormat;
    medium?: StrapiMediaFormat;
    large?: StrapiMediaFormat;
  } | null;
  hash: string;
  ext: string;
  mime: string;
  size: number;
  url: string;
  previewUrl: string | null;
  provider: string;
  createdAt: string;
  updatedAt: string;
}

export interface StrapiMediaFormat {
  name: string;
  hash: string;
  ext: string;
  mime: string;
  width: number;
  height: number;
  size: number;
  path: string | null;
  url: string;
}

export interface StrapiResponse<T> {
  data: T;
  meta: {
    pagination?: {
      page: number;
      pageSize: number;
      pageCount: number;
      total: number;
    };
  };
}

// ==========================================
// Content Types
// ==========================================
`

    // Generate interfaces for each content type
    const apiContentTypes = contentTypes.filter((ct) => ct.apiID && !ct.plugin)
    console.log(
      `📝 Generating interfaces for ${apiContentTypes.length} API content types:\n`
    )

    apiContentTypes.forEach((contentType) => {
      console.log(
        `   - ${contentType.apiID} (${contentType.schema.displayName})`
      )
      output += generateInterface(contentType)
    })

    // Ensure output directory exists
    const outputDir = path.dirname(OUTPUT_FILE)
    if (!fs.existsSync(outputDir)) {
      fs.mkdirSync(outputDir, { recursive: true })
    }

    // Write to file
    fs.writeFileSync(OUTPUT_FILE, output)

    console.log(`\n✅ Types generated successfully!`)
    console.log(`📄 Output: ${OUTPUT_FILE}\n`)
    console.log(`💡 Import in your code:`)
    console.log(
      `   import type { Blog, Page } from '@repo/shared-data/strapi-types';\n`
    )
  } catch (error) {
    console.error("\n❌ Error generating types:", error.message)
    if (error.message.includes("ECONNREFUSED")) {
      console.log("\n💡 Make sure Strapi is running on", STRAPI_URL)
    }
    if (error.message.includes("401") || error.message.includes("403")) {
      console.log(
        "\n💡 Check your STRAPI_API_TOKEN is valid and has proper permissions"
      )
    }
    process.exit(1)
  }
}

// Run generation
generateTypes()
